### ISSUE TITLE
Reestructurar los tests

### ISSUE THREAD

**Issue by leliel12** [vcristiani/galaxy-chop#96]
- [x] Los fixtures y las configuraciones para tests (que creo que aun no hay ninguna) pueden estar en un archivo aparte llamado `tests/conftest.py`. Mover todos los fixtures ahi.
- [x] Remover esta linea https://github.com/vcristiani/galaxy-chop/blob/95b966c32a563e7a85d5990abdb83d93618d186c/tests/test_input.py#L28
- [x] Los archivos de tests tienen que tener el nombre del modulo que prueban `tests/test_core.py`, `tests/test_util.py`.
- [x] Mover todos los datos de tests en legacy a `tests/test_data`. Incluso pueden tener algo como `tests/test_data/real` para las galaxias reals (asumo esta estructura de aca en mas)

- [x]  Los paths no pueden estar harcodeados (siguiente seccion).

# Sobre la forma de tratar a los paths

La forma canónica de acceder al path donde se encuentra el script actual es:

```python
PATH = os.path.abspath(os.path.dirname(__file__))

TEST_DATA_PATH = PATH / "test_data"
```

Esto nos daria el path completo y absoluto hasta `tests/conftests.py`, en mi cado `/home/juan/proyectos/galaxychop/src/tests`

De ahi en mas se pueden reemplazar linead como estas

https://github.com/vcristiani/galaxy-chop/blob/95b966c32a563e7a85d5990abdb83d93618d186c/tests/test_input.py#L391-L393

por algo como

```python
dm = np.loadtxt(TEST_DATA_PATH / "real" / "dark.dat") 
s = np.loadtxt(TEST_DATA_PATH / "real" / "star.dat") 
g = np.loadtxt(TEST_DATA_PATH / "real" / "gas_.dat") 
```

**Comment by antotaverna** [comment]
About item 2. I can't remove the random line in conftest.py becouse the fixtures "disc_xrotation", "disc_yrotation", "disc_zrotation", and "halo_particles" need the random.

@leliel12  what do you suggest?, An option is define the random line inside each fixture

**Comment by leliel12** [comment]
```python
@pytest.fixture(scope="session")
def halo_particles(mock_dm_halo):
    """Spherical mock halo."""
    
    def make(size, seed=None):
        random = np.random.RandomState(seed=seed)
        mass_dm, pos_dm = mock_dm_halo(N_part=size)
        vel_dm = random.random_sample(size=(size, 3))

        return mass_dm, pos_dm, vel_dm
        
    return make
```

se usa

```python
def test_zaraza(halo_particles):
    
    halo_particles = halo_particles(size=100, seed=42)
    
    ...
    
```

Por otro lado si los parametros de make en uno seed esta primero que en 
**todos** este primero

**Comment by vcristiani** [comment]
the way to access the paths was resolved in #102

**Comment by vcristiani** [comment]
this closes with #103
